# Generated by Django 2.2.16 on 2021-01-07 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('director', models.CharField(max_length=200, null=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Poster')),
            ],
        ),
    ]
